### ISSUE TITLE
Update marketplace installation procedure

### ISSUE THREAD

**Issue by tirix** [glacode/yamma#10]
I believe the [description of the installation procedure on the marketplace](https://marketplace.visualstudio.com/items?itemName=glacode.yamma&ssr=false#overview) is dated and can be much simpler now?
It still has git clone, node.js installation etc., which I believe is not required anymore.

**Comment by glacode** [comment]
I guess it's inheriting the GitHub instructions (that are meant for a developer). Isn't it?

I should look at how I can provide Marketplace "custom" instructions.

I never install it from the marketplace: which text would you suggest?

**Comment by tirix** [comment]
I'm thinking something along the lines of #11.
Once merged, maybe generate a new VsCode Marketplace release version.

**Comment by glacode** [comment]
ver. 0.0.8 has been published, thank you for your useful PR
