### ISSUE TITLE
Unknown language in `contributes.grammars.language`. Provided value: yamma

### ISSUE THREAD

**Issue by tirix** [glacode/yamma#5]
I have this message in the extension's "Runtime Status":
`Unknown language in `contributes.grammars.language`. Provided value: yamma`

Could that be an issue?
<img width="632" alt="image" src="https://user-images.githubusercontent.com/5831830/235314557-ebdc805c-6262-4660-8c66-b180e84d65f7.png">

**Comment by tirix** [comment]
I see the following in `package.json`:
```
	"contributes": {
		"languages": [
			{
				"id": "Yamma",
				"aliases": [
					"Yamma",
					"Metamath"
				],
				"extensions": [
					".mmp"
				],
				"configuration": "./language-configuration.json"
			}
		],
		"grammars": [
			{
				"language": "yamma",
				"scopeName": "source.mmp",
				"path": "./syntaxes/mmp.tmLanguage.json"
			}
		],
```
I wonder if VsCode is case-sensitive for the LanguageId and does not match `"id": "Yamma"` with `"language": "yamma"`?

**Comment by glacode** [comment]
I'm now using semantic tokenization, thus the static grammar file is not even used (it's still there for "historical" reasons)

Do you get semantic tokenization?

**Comment by tirix** [comment]
> I'm now using semantic tokenization, thus the static grammar file is not even used (it's still there for "historical" reasons)

Ok!

> Do you get semantic tokenization?

I'm not sure semantic tokenization works either, though. Here is the syntax highlighting I get:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/5831830/235320146-4eb796ee-06f9-4d9e-8a18-ced580796f9d.png">

**Comment by glacode** [comment]
it should work with .mmp files

Yamma is a .mmp extension that does full verification / some diagnostic on .mm files and full verification / serious diagnostic on .mmt files

But semantic tokenization works only with .mpp files

**Comment by tirix** [comment]
I don't have the error message with version 0.0.3 anymore.
Closing this one too!
